### ISSUE TITLE
Planned audio changes

### ISSUE THREAD

**Issue by franc-ist** [Cog-Creators/Red-DiscordBot#185]
# **_Planned improvements to audio module:**_
## Todo:
- [x] Means under development

**Definite:**
- [x] queue-playlist integration
  - songs put in the queue will be played next after the current song finishes. once the queue is empty, playlist resumes.
  - when a queue is playing, adding a playlist puts it at the end of the current songs being played.  
- [x] playing on a repeating "current" playlist
- [x] adding/removing songs to current
- [x] adding/removing playlists to current
- [ ] playlist management
  - saving current songlist as playlist
  - adding/removing songs/playlists to x playlist
- [ ] queue management
  - removing x song from queue
  - moving songs around in the queue
- [ ] add sfx by link
- [ ] disable loop without !stop
- [x] When adding a song, don't just say "a song has been put in the queue" and don't just stick "a song" in the queue. Put in the search string, and then update it once the song name/url is found.
- [ ] Display current song duration/time till added song
  - 1:40 [███████...............] 3:21 <- updating every time !song is used
- [ ] Fix the reload bug in #155 
- [ ] Fix the bug in #153 
- [ ] Really redo how audio handles multiple servers
- [ ] asyncio bug in #132
- [ ] Make sure that mobile/desktop links work as in #80 
- [ ] Separate youtube search command #79 
- [ ] Make bot auto-disconnect after x seconds
- [x] Make the bot display the file name of local tracks, instead of the path
  - In queue, and actually show in currently playing

**Not so definite:**
- [ ] Remove/rethink !play. Just have !queue functionality. give mods/admins/owner some way to override instead. maybe just through moving songs in queue
- [ ] Radio solutions
  - icecast/shoutcast/last.fm https://github.com/Twentysix26/Red-DiscordBot/issues/179
  - pandora/spotify
- [ ] Discord.py dependent fixes
  - Join multiple voice channels (when discord.py supports)
  - remove song from status - stick into channel details?
- [ ] Features specified by #52 
- [ ] Features specified by #135 
- [ ] Features specified by #180 
## Submitted for review
- [x] Means under test
- [x] Queue/Playlist integration.
  - adding a song to the queue doesn't remove the playlist.
  - once the current song finishes, the queue plays
  - the queue must finish before playlist resumes.
  - if a playlist is started while a queue is playing, the queue must finish before the playlist will start.
- [x] Link resolving
  - `!queue willow` --> [SEARCH:]willow has been put into the queue by irdumb#1229
  - after giving it some time to resolve,
    - `!queue` --> Videos in queue: 1. Jasmine Thompson - Willow (Lyrics)
- [ ] Settable skip percentage
  - settable % votes needed to exceed to skip. 50 == majority
- [ ] Make the bot display the file name of local tracks, instead of the path
  - In queue, and actually show in currently playing
## Accepted
- [x] Means accepted for merge
- [ ] Means ready to merge
- [ ] Volume changes
  - `!audioset volume` by itself displays the current volume
  - range changed from 0-1 to 0-100

**Comment by irdumbs** [comment]
for non-streaming radio solutions, hope to integrate it with queue

just some notes. I'm thinking..
playing_playlists = [pl1,pl2]
current_songlist = [copy of contents of playling_playlists]
current_song = index to ^
when song added as a queue song, put into current_songlist after current_song
when !shuffle, shuffle all songs after queue and current_song
when current_songlist is done, copy playing_playlists as current_songlist

had a reason for doing it that way as apposed to a priority queue, but now I forgot what it was....
maybe so that I can do !prev?

**Comment by tekulvw** [comment]
You guys planning on modifying the current audio module or rewriting it?

**Comment by franc-ist** [comment]
@tekulvw both, if necessary

**Comment by tekulvw** [comment]
Okay I vote for a rewrite, leave your reactions as votes. I am also going to close all the audio related issues that are now encompassed by this

**Comment by DomGrieco** [comment]
Have you guys considered making it so we can run multiple bots using the same local audio directory? Maybe I'm missing something and you can already do this? I'm running 4 bots basically for music for the users.

**Comment by Kowlin** [comment]
@DomGrieco this can be avoided as soon as Discord.py updates there way of handling audio so that bot accounts can support that behaviour. So far there is no ETA on that subject from Discord.py's end

**Comment by hjri** [comment]
@DomGrieco can't you use symlinks\binds to accomplish that?

**Comment by Kowlin** [comment]
@hjri For what I can gather the bot will run local tracks from `data/audio/playlists/folder`. It sure is a solution but it might be unstable. (Not that I see any way that it could be unstable)

**Comment by franc-ist** [comment]
![](https://i.imgur.com/g3gg3J7.png)

**Comment by irdumbs** [comment]
heya franny ( ͡° ͜ʖ ͡°)

**Comment by franc-ist** [comment]
heya dumb @irdumbs .

**Comment by franc-ist** [comment]
prettified the list

**Comment by franc-ist** [comment]
Closed due to #225
