### ISSUE TITLE
General list of things to do

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#187]
Feel free to comment with suggestions
- [ ] ~~Import plugins as modules~~
- [ ] Nested commands
- [ ] ~~Better command parsing~~
- [x] ~~Separate Owner commands into Owner plugin #188~~
- [ ] Scheduled file flushers
- [ ] Base plugin class
  - infilter
  - outfilter
- [ ] `--debug` flag
  - And start flags in general
  - `--daemon`?
- [x] Global permission changes (see tekulvw/Squid-Plugins)
- [ ] Global config
- [ ] commands costing currency
- [x] ~~`aliaslist` to `alias list` #195~~
- [x] Server specific bank \* #201
- [x] ~~Make aliases case insensitive #195~~
- [x] ~~Auto generate oauth URL for bot accounts #196~~
- [x] Add `bot` to globals in debug
- [ ] Override `on_error` to provide some better permissions error messages
- [ ] Choose which cogs to update
- [ ] Audio improvements? https://github.com/Twentysix26/Red-DiscordBot/issues/271

\* _denotes currently in development_

**Comment by irdumbs** [comment]
- commands optionally costing economy currency
- customizable command permissions #41
  - per user
  - per role
  - per channel
  - per server
  - per time??

**Comment by franc-ist** [comment]
restrict `!bank set` to owner only. i'm fed up of people fucking up my leaderboard by cheating

**Comment by irdumbs** [comment]
perhaps choose your admins more carefully 😉

**Comment by franc-ist** [comment]
@irdumbs its not that. somehow my bot has made its way onto 5 servers i dont own, and people are cheating

**Comment by irdumbs** [comment]
lolol
That's actually an issue with economy.py
It's bank should be server-specific

**Comment by franc-ist** [comment]
Remove user details from cogs (e.g. economy) when the bot leaves a server

**Comment by franc-ist** [comment]
#219

**Comment by franc-ist** [comment]
`NameError: name 'bot' is not defined` when calling a debug alias

**Comment by irdumbs** [comment]
fix debug not having bot in lambdas
`[p]debug (lambda: bot.say('hi'))()`
should work to be backward compatible

**Comment by kanahanazawa** [comment]
hiya. cant add people to blacklist that have a space in their name. guessing that would also count for whitelist? tired of certain users playing troll songs. also, i tried using the new nickname feature in discord to remove the space but that doesn't work guessing cause its not their actual name.

**Comment by irdumbs** [comment]
this is not the place to ask that.
deal with spaces by surrounding their name "with quotes" or just @mention them

**Comment by dataXploit** [comment]
streamalerts for youtube streams would be nice

**Comment by YeahImRose** [comment]
I've been working on a cog to make commands cost a customizable amount of a currency. The currency itself could be either automatically given to users(e.g 5 per hour, 100 per day, etc) or have a claiming system similar to `[p]payday`. I will probably upload a version of this to my repo once I get it fully operational :)

**Comment by tekulvw** [comment]
Should be fairly easy to implement using the same kind of system as permissions

**Comment by tekulvw** [comment]
Hasn't been touched in a while, I'll let this slide into oblivion
