### ISSUE TITLE
[Audio] Suggestions for rewrite

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#2494]
This issue is to gather features to be suggested for or worked on for Audio after 3.1 is released. This supersedes and replaces #623.

Current items in process that are more prominent on my todo list (July 2019):

- [ ] get_tracks -> load_tracks
- [ ] AudioTrack objects: will hold Lavalink Tracks and localtrack items (no more str handling for local tracks/use Path objects)
- [ ] expose FriendlyExceptions for tracks to the users
- [ ] playlist save fix (will overwrite playlists with no confirmation) *
- [ ] playlist txt file (playlist upload/playlist download) rework. Two file options: v2 style (list of urls, only yt and soundcloud urls allowed) and v3 style (Lavalink Track information should be stored and not urls where Lavalink will need to refetch the Track information) *
- [ ] add more comments to explain things that are not clear
- [ ] move playlists to a custom Config group and add code to automatically migrate existing playlists to the new structure *
- [ ] global, guild and user scope on saved playlists *

Background/Feature todo:

- [ ] autojoin/bind (a command to bind the bot to a text channel and a voice channel for the duration of the audio session), also setting a lock on the audio set notify channel via this method *
- [x] ~~channel check for auto-moving channels with a new command/if the user moved~~ (#2521)
- [ ] toggle for autopause when no one is in the channel (#721)
- [x] ~~add pagination to audiostats command~~ (in #2533)
- [ ] queue: move songs up and down the list by number of songs (#621)
- [ ] replay queue history by day (#366) *
- [ ] autoplay songs when playlist runs out (musicbot style) (#623) *
- [ ] local: pls, m3u support (#620) (make custom parser or contribute to Lavaplayer/Lavalink) 
- [ ] remove multiple songs at once *
- [ ] url or keyword blacklist *
- [x] ~~audioset setting to join full voice channels (bot needs Move Members to make this happen)~~ (#2525)
- [ ] if a playlist has a playlist url saved (non-custom playlist), check the URL for new songs to import (#1845, #270)
- [ ] support timestamps in urls, like https://youtu.be/8CdcCD5V-d8?t=31
- [ ] playlist improvements (#1544)
- [ ] a thumbsup/thumbsdown on a np message to make a song play more frequently on a playlist in tandem with the playlist checking on 1544, + skip stats (playlist playing stat saving/management)
- [ ] child folders within "album" folders in localtracks (#270)
- [ ] queue doesn't reflect actual order of songs when shuffle is applied because shuffle is random choice out of the queue

Considering:

- [ ] Split off Spotify functions to its own file in the audio folder, i.e. spotify.py *

What about sfx?
sfx can be found (unapproved) at: https://github.com/baiumbg/baiumbg-Cogs . Use at your own risk.

Items with ( * ) are marked for Draper#6666 to consider working on. Anyone else could make these items too... but maybe ask in the Red discord server if he's started on them, or if I have, thanks.

**Comment by Jackenmen** [comment]
Could you explain better what you mean by autojoin/bind? I have troubles understanding what you want it to do. :/

**Comment by aikaterna** [comment]
I mean exactly what I wrote above, a command to lock the bot to a specific voice channel and text channel for audio commands for that current voice session only. There are other audio bots that have this feature and it's been requested occasionally.

**Comment by Drapersniper** [comment]
Working on #2861

**Comment by Drapersniper** [comment]
Splitting the Spotify api functions has been done on #2890

**Comment by Drapersniper** [comment]
We we want to do the following (I assume this is while DJ role is enabled)
![image](https://user-images.githubusercontent.com/27962761/61522020-65271b00-aa09-11e9-9d27-6ead8abfdc91.png)

**Comment by Drapersniper** [comment]
So don't forget:

- Play tracks as they are queued  (queing Albums or playlists)
- Edit lock to  not allow enqueing single tracks while a playlist is enqueed

Aika if I forgot anything feel free to update the main issue  and i'll pick it up

**Comment by Drapersniper** [comment]
Consolidating everything in 1 place...

### Done:
- [x] ~~playlist save fix (will overwrite playlists with no confirmation)~~ (#2861 )
- [x] ~~playlist txt file (playlist upload/playlist download) rework. Two file options: v2 style (list of urls, only yt and soundcloud urls allowed) and v3 style (Lavalink Track information should be stored and not urls where Lavalink will need to refetch the Track information)~~  (#2861 )
- [x] ~~move playlists to a custom Config group and add code to automatically migrate existing playlists to the new structure~~  (#2861 )
- [x] ~~global, guild and user scope on saved playlists~~  (#2861 )
- [x]   ~~Split off Spotify functions to its own file in the audio folder, i.e. spotify.py~~ (#2890 )
- [x]  ~~if a playlist has a playlist url saved (non-custom playlist), check the URL for new songs to import~~   (#2861 )
- [x]  ~~autoplay songs when playlist runs out (musicbot style) (#623)~~ (#2890 )
- [x]  AudioTrack objects: will hold Lavalink Tracks and localtrack items (no more str handling for local tracks/use Path objects)
- [x]  get_tracks -> load_tracks (At the moment it just mirrors get_track, need to discuss with Aika how should audio implement so I can update my PR to use it the appropriate way)
- [x]  child folders within "album" folders in localtracks (#270)
- [x]  url or keyword blacklist 
- [x]  support timestamps in urls, like https://youtu.be/8CdcCD5V-d8?t=31 (Partial pending changes to lava lib)
- [x] queue doesn't reflect actual order of songs when shuffle is applied because shuffle is random choice out of the queue

### Work started:
- [ ]  add more comments to explain things that are not clear

### Considering:
- [ ]  autojoin/bind (a command to bind the bot to a text channel and a voice channel for the duration of the audio session), also setting a lock on the audio set notify channel via this method 
- [ ]  replay queue history by day (#366) 
- [ ]  remove multiple songs at once 
- [ ] queue: move songs up and down the list by number of songs (#621)
- [ ] remove multiple songs at once *
- [ ] Make playlist remember where it was stopped? (#1544)

### Others Changes:

- Playlist now start playing after first song is loaded instead of waiting for the full playlist to load
- Lavalink response is now cacheable as part of #2890  (Signicantly faster loading, 2.7K songs went from 1 hour to 30 seconds on folow up enqueues ) 
- As part of #2890 Users are no longer able to enqueue any tracks while a playlist is enqueuing, this is to ensure queue order persists. But since songs now start being played the moment they are loaded, This doesn't have a major negative impact to users.

**Comment by Drapersniper** [comment]
Full support for these will be available if/when https://github.com/Cog-Creators/Red-Lavalink/pull/61 is Merged
1. queue doesn't reflect actual order of songs when shuffle is applied because shuffle is random choice out of the queue
2. support timestamps in urls, like https://youtu.be/8CdcCD5V-d8?t=31

**Comment by aikaterna** [comment]
Closing in favor of Draper's list @ #2940
