### ISSUE TITLE
[3.1] Mod Sprint

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#2500]
With 3.1 closing in with #2499, I've collated a list of various issues and pull requests previously suggested on this repo. If I'm missing anything, feel free to either [open an issue](https://github.com/Cog-Creators/Red-DiscordBot/issues/new/choose) about it or comment below.

- [x] **#2501: Class compositing**
  - [ ] #2501: Move some Mod functionality to Core.
- [x] #2512 | #2501: Immediate modlog
- [ ] #2490: Move modlog-based listeners to modlog
- [ ] #2441: Default days for [p]ban
- [ ] #2437: Customize deleterepeats
- [ ] #2282: Global users with [p]userinfo
- [ ] #2231: Mute improvements
  - [ ] #2103 | #2140: Temporary Mutes
  - [ ] #1852: Guild mute by role
  - [ ] #1607 | #2599: Mute by category
  - [ ] #2179 | #2599: Mute quality of life
    - [ ] Remove voice mute / unmute
    - [ ] Category mute / unmute
    - [ ] Mass mute / unmute info logging
    - [ ] Target other channels with mute / unmute
    - [ ] Mute / unmute default to channel / category
  - [ ] Mute dodging by leaving / rejoining guild

**Comment by mikeshardmind** [comment]
Adding to this, we need to ensure all modlog creations are made prior to sending any feedback in context channel, see #2512
