### ISSUE TITLE
Future Audio Work

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#2940]
This issue is to gather features to be suggested for or worked on for Audio this supersedes and replaces #2494 due to the changes added by #2904

### Open Issues: 
- [ ] Lavalink status (#1811)
- [ ] Document Lavalink setup with multiple instances (#2843) (This could also send a message to the bot owner)

### TODO:
- [ ] Queue: move songs up and down the list by number of songs (#621)
- [ ] Break Search command into multiple subcommands
- [ ] Wastebin lists of links to tracks
- [ ] Remove multiple songs at once
- [ ] Make Queue aware when enqueuing playlists and/or albums
- [ ] Add more dispatches
- [ ] Add more public APIs to allow for more Audio add-ons 

### Requests:
- [ ] Make playlist remember where it was stopped? (#1544)
- [ ] Google Play Music Support (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md)
- [ ] SFX support
- [ ] `[p]prev` Can go back multiple songs > This will be easier if #366 is addressed
- [ ] Play multiple songs at once `[p]play 1|2|3` for example
- [ ] Local: M3U/M3U8/PLS/XSPF/WPL/ASX/iTunes Playlists support (#620) (make custom parser or contribute to Lavaplayer/Lavalink)
- [ ] Parse tracks out of a M3U and PLS url
- [ ] Repeat the whole queue
- [ ] `[p]play` and `[p]playlist append` commands to bulk enque multiple songs
### Maybe:
- [ ]  A thumbsup/thumbsdown on a np message to make a song play more frequently on a playlist in tandem with the playlist checking on #1544, + skip stats (playlist playing stat saving/management)
- [ ] Lyrics support
- [ ] Expand Spotify playlist support to use SoundCloud API
- [ ] Jukebox price to be charged per song instead of per command?
- [ ] Pillow Audio 😝 
- [ ] Add RPC functionality; information on doing this at #3741
- [ ] add `[p]makeplaylist` that enqueue n number of recently played tracks in the server
- [ ] add `[p]playstric <author> || <track name>` which would allow using Global Cache and JDA cache directly.
- [ ] Add special casing for Live stream playlists

### Next Todo
- [ ] Autojoin/bind (a command to bind the bot to a text channel and a voice channel for the duration of the audio session), also setting a lock on the audio set notify channel via this method, pinned queue
- [ ] Configurable limit on max concurrent audio streams (#272)
- [ ] More Spotify functionality using their API
  - Search for Artists, Playlists and Albums
  - Use Song Metadata for info
  [ ] Spotify Search command
- [ ] Absolute Vote toggle (Voting system that DJ's can't bypass)
- [ ] Auto Join a music channel

## In Edge
- [x] `[p]audioset role` To accept a list of roles
- [x] Set maximum allowed volume
- [x] Effects
- [x] Channel specific volume settings
- [x] Configurable maximum queue size - Places where the Queue is Controllate already been added, now need to add a command to set it. (Note to self, Hard coded > Bot Owner > Server Mods)
- [x] Add a `[p]mixplaylist <url>` command based on the newly discovered behaviour of youtube mix playlists - https://github.com/Cog-Creators/Red-DiscordBot/issues/2940#issuecomment-583879466

### Done
- [x] Persist queues on reboot/reload Done in #3242 but want to make it avaliable as part of #3459

#### What about sfx?
- sfx can be found (unapproved) at: https://github.com/baiumbg/baiumbg-Cogs . Use at your own risk.

#### Want to suggest something?
- Just leave a comment below!

**Comment by Jackenmen** [comment]
Unless this feature is already proposed somewhere, I would like to propose option to be able to use `[p]prev` to be able to go more than one song backwards and also to be able to use it with shuffle enabled - similarly to how it is in regular music players.

**Comment by Drapersniper** [comment]
Currently it will work with Shuffle (with #2904 ), but not more than 1 song, so i'll add that

**Comment by Vexed01** [comment]
As we [discussed in Discord](https://discordapp.com/channels/133049272517001216/160386989819035648/615982511268298776), a possible feature is allowing server owners/admins to move playlists between servers they own/administrate in.
A possible change to this original idea is that a non admin/owner user in server A can then copy a playlist to server B if they have admin/owner perms where the playlist is being copied to.
These would only apply for guild playlists.

**Comment by Drapersniper** [comment]
@Vexed01 this would overcomplicate the existing playlist perms quite a bit, privacy is also a concern. and as such am Against this.

However ... Currently you'll be able to copy a playlist from guild A to the User Scope and from the User scope to the Guild scope on Server B.

This allows less cross server information display, and if they really want to copy cross server a 2 step proccess seems okay to me.

**Comment by Vexed01** [comment]
That's fine, I wasn't expecting much. It was just an idea!

**Comment by Jackenmen** [comment]
Hmm, I have another proposition, option to limit the range for volume command? I saw someone that wanted such feature before so that he could enable users to change volume but not let them change it from for example 50% to 150% which would annoy everyone in vc.

**Comment by Ianardo-DiCaprio** [comment]
Ability to add multiple songs in the play command by separating the songs with a character that's not used often such as "|". Which would be used like `[p]play Eminem Lucky You | Joyner ADHD` and it adds both songs.

**Comment by ltukezl** [comment]
I mostly use redbot for playing local songs and it works pretty well for basic operation of !play "path/music.mp3"
Would it be possible to have commands such as !play "folder" to enqueue all music in that folder.
!local folder is extremely cumbersome since i wouldn't want to transfer all my files to new "localtracks" folder.
For my use case navigation and stuff like that isn't really a concern since i'm always using "copy as path" with windows.

**Comment by Drapersniper** [comment]
@ltukezl possible it is, however for privacy reason I’m agaisnt being able to pass a local path to the bot for play, as of 3.3 you are able to create symbolic links so you don’t need to copy the files into the local tracks folder, the reason the local tracks folder exist is due to the aforementioned privacy concerns.

**Comment by ltukezl** [comment]
Fair. symlinks feels decent enought workaround.
Thank you.

**Comment by Drapersniper** [comment]
The above said it’s not a hard no, if you can give some examples of use cases where it would prove beneficial to all users and not just yourself, I’m more than happy to look into the possibilities.

**Comment by ltukezl** [comment]
Since it already worked for regular mp files I didn't really concern too much about the possible privacy issues. 

While the symlink does function well (EDIT subfolders with music doesn't work, returns nothing found. maybe it's on my end so i'll debug it tomorrow) , it doesn't really scale too well to my 400 albums. So my enchantment suggestions would fall either into the !local folder enchantments such as skip 10 menus and show more albums per menu.
Maybe it could accept the path via DM where the owner might be more likely to post private info or with enought rights the bot could instantly delete messages that has been processed as local path / folder.

Either way I don't really have good solution on hand but I recon queuing whole folders easier would still be beneficial to some portion of users.

**Comment by Drapersniper** [comment]
Nothing found after you select play or nothing found as in the folder doesn’t get shown? This is no longer something that shouldn’t be in this issue please take any further issue to our discord server and we can talk there. I’m interested to understand exactly what you mean by not found as in when and where it happens

**Comment by Drapersniper** [comment]
Blocked by #3459

**Comment by aikaterna** [comment]
Have a command, most likely usable for server owners, bot owners, bot mod, bot admin that toggles on a bias for lyrics-based song titles via a yt search. This would append "lyrics" to a [p]search query on first glance (could def be implemented differently), and in regards to the idea of the audio track API/caching idea that Draper has, could prioritize cached tracks with lyrics in the song title or similar.

**Comment by Drapersniper** [comment]
Add a `[p]mixplaylist <url>` command based on the newly discovered behaviour of youtube mix playlists

**Comment by Drapersniper** [comment]
MAYBE: add `[p]playstric <author> || <track name>` which would allow using Global Cache and JDA cache directly.

**Comment by Drapersniper** [comment]
add `[p]makeplaylist` that enqueue n number of recently played tracks in the server

**Comment by PredaaA** [comment]
Show the enqueued playlist name (and url?) when using genre command.

**Comment by fixator10** [comment]
![thingie](https://moeka.is-a-good-waifu.com/4jYLpGU.png)

**Comment by Drapersniper** [comment]
~~I won't be continuing work here, I wont close this issue as its a good way to congragate all feature requests and work. hopefully it assists Aika and anyone else working on Audio in the future.~~

**Comment by NeuroAssassin** [comment]
Add RPC functionality; information on doing this at #3741

**Comment by Drapersniper** [comment]
Add special casing for Live stream playlists
Note: Users wont be mix livestream with normal songs due to special casing, but this will allow playlist to always have accurate livestream data

**Comment by Drapersniper** [comment]
`[p]audioset role` To accept a list of roles?

**Comment by Drapersniper** [comment]
Adding this here to cleanup original post

### Completed:
### Somewhere (Deffo in #3459):
 - [x] Show the enqueued playlist name (and url?) when using genre command.
 - [x] Toggles on a bias for lyrics-based song titles via a yt search
#### In #2904:
- [x] Toggle for autopause when no one is in the channel (#721)
- [x] Autoplay songs when playlist runs out
- [x] Url or keyword blacklist
- [x] If a playlist has a playlist url saved (non-custom playlist), check the URL for new songs to import
- [x] Support timestamps in urls, like https://youtu.be/8CdcCD5V-d8?t=31
- [x] Child folders within "album" folders in localtracks (#270)
- [x] Queue doesn't reflect actual order of songs when shuffle is applied because shuffle is random choice out of the queue
- [x] Global, guild and user scope on saved playlists in 
- [x] Move playlists to a custom Config group and add code to automatically migrate existing playlists to the new structure
- [x] Playlist txt file (playlist upload/playlist download) rework. Two file options: v2 style (list of urls, only yt and soundcloud urls allowed) and v3 style (Lavalink Track information should be stored and not urls where Lavalink will need to refetch the Track information)
- [x] Playlist save fix (will overwrite playlists with no confirmation)
- [x] AudioTrack objects: will hold Lavalink Tracks and localtrack items (no more str handling for local tracks/use Path objects)
- [x] get_tracks -> load_tracks
- [x] Split off Spotify functions to its own file in the audio folder, i.e. spotify.py
#### In #2950:
- [x] Play + Bump Combo Command (#2522) 
- [x] Migrate Menus to use Menus from #2809
- [x] Don't shuffle bumped tracks (**Added an extra argument to `[p]shuffle` that allows the person with permissions to say whether bumped tracks should be shuffled or kept at the top of the queue, off by default**)
- [x] Queue embed to update the bar every x seconds (**Added a button to `[p]queue` that allows the queue to be updated to the current status, will not automate this due to Discords rate limits**)
- [x] Expand local track support to all file formats (**Added support for AAC, AU, M3U, M4A, OPUS, RA, TS, WAV, WMA, 3GP, FLV M4V, MKV, MP4, MOV, WEBM, WMV**)

#### In  #3085:
- [x] Expose FriendlyExceptions for tracks to the users
- [x] Replay queue history by day (#366, Done in #3199)
### in Other:
- [x] Expose FriendlyException on play command (#3085)
- [x] Allow Removing tracks from queue by URL (#3201)
- [x] Stop the player after multiple subsequential errors (#3165)
### Fixed:
#### In #2904:
- [x] `[p]audioset settings` reports Jar build incorrectly (#2880)
#### In #2950:
#### In Other:
- [x] Audio Bug after disconnect (#2711) in https://github.com/Cog-Creators/Red-Lavalink/pull/61
- [x] Fix an issue with mixplaylist being recognised as single tracks (#3104)
- [x] Restart Lavalink after unexpected shutdown (#3034)
- [x] An error throw in the event handler (#3168)
- [x] Fix a console spam (#3123)
- [x] Fixed a potential crash on commands (#3122)

**Comment by kristowyn** [comment]
As per conversation in `#support` could a __global empty disconnect__ feature be added to the bot's owner's perms?
That way, if 100 servers have the bot playing music to an empty VC or the bot not playing anything, it wouldn't use the excess hosting resources?

**Comment by Ryonez** [comment]
I'd like to seem some global audio settings for `emptydisconnect` and `emptypause`.

Personally, I don't like leaving things open if they aren't being used, and secondly because some users do feel uncomfortable about it.

I think an additional benefit would be a toggle for the bot owner to enforce these settings, so server owners/staff can't change them.

@Drapersniper (I think this was you) response on discord:

> Put it there
But realistically the way I'd implement is a global default that guilds can opt out of if they should choose
Rather than a global rule

My response:

> That's why I suggested that as a separate toggle. A bot owner might have limited bandwith and choose to allow the option to use audio, but enforce the global rules to save the bandwidth.
It allows for it to be set up for the circumstances required.

**Comment by Drapersniper** [comment]
Implement the "something when wrong ..." kinda message mentioned in #3868

**Comment by Drapersniper** [comment]
![image](https://user-images.githubusercontent.com/27962761/83281093-7c10cf00-a1cf-11ea-9cfb-9e61857f11d1.png)

**Comment by Jackenmen** [comment]
Draper told me we need something like this:
![image](https://user-images.githubusercontent.com/6032823/83339945-0d1c9e80-a2d3-11ea-8d06-d484dc12bf96.png)

**Comment by Drapersniper** [comment]
> Draper told me we need something like this:
> ![image](https://user-images.githubusercontent.com/6032823/83339945-0d1c9e80-a2d3-11ea-8d06-d484dc12bf96.png)

AAAAAAAAAAAAAAAAAAAAAAA

On java requirement failure message, link to docs for instructions on how to get supported java

**Comment by Kowlin** [comment]
I've been told to blame @jack1142 on this.

![firefox_tG7gEGCk8K](https://user-images.githubusercontent.com/10947836/83365199-c1d3c000-a3a6-11ea-8098-b08f47f901a3.png)
![firefox_Z0BhXQ6oUy](https://user-images.githubusercontent.com/10947836/83365200-c1d3c000-a3a6-11ea-9a5e-edbcd0bbb35a.png)

**Comment by Dav-Git** [comment]
Remove ``%`` in ``[p]volume`` help menu. Having it just say "Set the volume 1-150" seems more user-friendly and intuitive

**Comment by Drapersniper** [comment]
The way how volume will work is going to significantly change. In a future update if everything goes to plan, but I'll keep that in mind.

The problem with saying just 1-150 is that is an number without any context , that's the diff between between 100 and 110 in, eith percentage we know that that's a 10% increase and not a .. exponential increase where the value doubles every n stead


Note: could just edit the usage arg rather than the docstrings

**Comment by aikaterna** [comment]
Would be nice perhaps to have a Lavalink log upload command to post the spring.log file, but would only really work on internally run jars. Could help in support when folks are asking for logs. Most users can provide logs and not have much trouble getting them uploaded to hastebin or somewhere else, but this idea would make it even more easy for them. I'm not totally sold on adding this but thought I'd mention it as it may be helpful.

**Comment by Drapersniper** [comment]
> Would be nice perhaps to have a Lavalink log upload command to post the spring.log file, but would only really work on internally run jars. Could help in support when folks are asking for logs. Most users can provide logs and not have much trouble getting them uploaded to hastebin or somewhere else, but this idea would make it even more easy for them. I'm not totally sold on adding this but thought I'd mention it as it may be helpful.

I'm actually sold. We could see if it's external and if external tell them how to find it instead. And if internal we just send the file in a message

**Comment by aikaterna** [comment]
Allow chaining on playlist start, like [p]playlist start playlist1 playlist2 playlist3

**Comment by PredaaA** [comment]
It would be really cool to implement this. For more care about resources usage.
![image](https://user-images.githubusercontent.com/46051820/98958963-1d33dd80-2503-11eb-8eaa-99c54d8d2b23.png)

**Comment by aikaterna** [comment]
Add support for YouTube music api, non async ref can be found at https://github.com/sigma67/ytmusicapi/tree/master/ytmusicapi

**Comment by aikaterna** [comment]
Add a playlist search command to be able to search for tracks on a saved Red playlist, the output would return artist/title/link like many of the other song displays (queue, playlist info, etc)

**Comment by Drapersniper** [comment]
Would we want to also add enqueue functionality allowing you to play the search result ?

**Comment by aikaterna** [comment]
Possibly, my use case was trying to search a saved playlist for specific artists so that I could remove them with playlist remove commands.

**Comment by npc203** [comment]
some default audio eq presets would be cool(i am aware of how to save eq configs). idk how to justify the need but somewhere on the lines of red having default songs maybe. Would be useful to show off how eq is cool.

**Comment by Drapersniper** [comment]
> some default audio eq presets would be cool(i am aware of how to save eq configs). idk how to justify the need but somewhere on the lines of red having default songs maybe. Would be useful to show off how eq is cool.

Yeah planning to do this on the rewrite and give users a handful of premade presets such as base boos, piano, voice etc

**Comment by Pogogo007** [comment]
Make Query option 5 (JDA) optional on GlobalAPI and implement on audio (Draper on disc)

**Comment by wcrigger** [comment]
We use RedBot to stream an Icecast URL, which is working flawlessly.  However, when poking around at audio features, I came across the  "[p] audioset status enable" command that updates the bot's status as to what is currently playing (sweet!).  However, after enabling the feature and having the first song updated as its status, subsequent songs in the same stream are not captured, or at least not set as the status of the bot as expected.  That first song it determines is playing becomes a static status for the bot.

I think it'd be really cool if RedBot could refresh its now playing data frequently (possibly at a configurable interval), and capture what is currently playing, and update its status accordingly.  I believe this can be achieved by sending the "Icy-MetaData" in the request header, and by reading the response "metaint" header and parsing it accordingly.  I found some example python code for this, and I think it'd be something along the lines of this:

  ```
  request.add_header('Icy-MetaData', 1)
    response = urllib2.urlopen(request)
    icy_metaint_header = response.headers.get('icy-metaint')
    if icy_metaint_header is not None:
        metaint = int(icy_metaint_header)
        read_buffer = metaint+255
        content = response.read(read_buffer)
        title = content[metaint:].split("'")[1]
        print title
```

...perhaps in a try/except block, where if successful, it updates the status as to what is currently playing, else, if failure, possibly blanking out the status, or outputting something generic.

Thanks in advance for the consideration.  You all have something really cool here!

**Comment by SnooPee508** [comment]
Hello! I have an awesome Idea! Is it possible in equalizer that bot owners can create global equalizer presets? So that adding filters like Bassboost, treble etc. If it is possible then we don't need to add separate filters command. This can come in handy :)

**Comment by fmohican** [comment]
Hello,
Currently I face a issues with nicely and lovely Red Audio (Cog?), let's get to the point....
I setup myself an instance of red on my Windows Server, everything went fine till i want to setup few playlists from **local albums**.

On a first hand i search a lot how to create playlists from local files, how to setup media patch without going on `C:\Users\[myuser]\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\[myInstanceOfRed]\cogs\Audio\localtracks` and i can't found anything.
I can't find any workaround for the files path, but i found an workaround for creating playlist so, i convert all files to mp3 pack into folders and then upload to `%appdata%\Local\Red-DiscordBot\Red-DiscordBot\data\[myInstanceOfRed]\cogs\Audio\localtracks`, everything went fine and smooth with follow commands
```
.local folder [name]
playlist queue [name] --scope Global
.stop
[repeat]
```
So as i said everything went fine till i have to repeat operation, every `playlist queue [name] --scope Global`  i have to wait 5 minutes to execute another, on a simple math 4 albumes (no matter how long/short are) i have to wait 20 minutes (in total).
It's frustrating not to be able to go over certain limits, even if it means taking risks, since we are talking about a selfhosted instance of Red and just as frustrated is waiting a few hours to get a job done that you can do in 20 minutes at most. 

To resume everything.
- Possibility to create playlist from local files without any cooldown or 'workaround'.
- Possibility to set custom cooldown on every command. (optionally a warning like, if you fall below a certain value, no more support is offered. You do it at your own risk. )

Transcript from discord: https://gist.github.com/fmohican/9bd522c9550ff787e8ca38c7751099d1

**Comment by Drapersniper** [comment]
> Hello,
> Currently I face a issues with nicely and lovely Red Audio (Cog?), let's get to the point....
> I setup myself an instance of red on my Windows Server, everything went fine till i want to setup few playlists from **local albums**.
> 
> On a first hand i search a lot how to create playlists from local files, how to setup media patch without going on `C:\Users\[myuser]\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\[myInstanceOfRed]\cogs\Audio\localtracks` and i can't found anything.
> I can't find any workaround for the files path, but i found an workaround for creating playlist so, i convert all files to mp3 pack into folders and then upload to `%appdata%\Local\Red-DiscordBot\Red-DiscordBot\data\[myInstanceOfRed]\cogs\Audio\localtracks`, everything went fine and smooth with follow commands
> 
> ```
> .local folder [name]
> playlist queue [name] --scope Global
> .stop
> [repeat]
> ```
> 
> So as i said everything went fine till i have to repeat operation, every `playlist queue [name] --scope Global` i have to wait 5 minutes to execute another, on a simple math 4 albumes (no matter how long/short are) i have to wait 20 minutes (in total).
> It's frustrating not to be able to go over certain limits, even if it means taking risks, since we are talking about a selfhosted instance of Red and just as frustrated is waiting a few hours to get a job done that you can do in 20 minutes at most.
> 
> To resume everything.
> 
> * Possibility to create playlist from local files without any cooldown or 'workaround'.
> * Possibility to set custom cooldown on every command. (optionally a warning like, if you fall below a certain value, no more support is offered. You do it at your own risk. )
> 
> Transcript from discord: https://gist.github.com/fmohican/9bd522c9550ff787e8ca38c7751099d1

Implementation of this allow. Appending/creating a playlist from an existing local folder.


Given the size of queues and potential risk from it I will not remove the cooldown here unless there's a lot of push back. If there is then I'm removing the 3 scopes and making playlist only creatable by bot owners

**Comment by fmohican** [comment]
> Implementation of this allow. Appending/creating a playlist from an existing local folder.
> 
> Given the size of queues and potential risk from it I will not remove the cooldown here unless there's a lot of push back. If there is then I'm removing the 3 scopes and making playlist only creatable by bot owners

There is no point for that cooldown on **local files** even old hdd can handle easy hundred of mp3s. There is a lot of time wasted on cooldown, as i said on transcript, for public bot it make sense, for self-hosted instance doesn't, since is my Server/IP/Files its my own responsibility to take care of them. Enforcing limits doesn't help everyone.

Also eliminating local playlists cause a dependency of platforms like youtube/spotify/etc... Don't get me wrong, i like to be in control of my data, even on discord.

**Comment by aikaterna** [comment]
Please keep arguments off this topic. Thanks.

**Comment by Ryonez** [comment]
> Given the size of queues and potential risk from it I will not remove the cooldown here unless there's a lot of push back. If there is then I'm removing the 3 scopes and making playlist only creatable by bot owners

Could you please go over the potential risks?
We could also have it so the bot owner gets to bypass the cooldown with a prompt maybe.

Edit: Response in Discord:
> in short, your bot can get ddosed and/or you could possibly corrupt your playlist files

**Comment by aikaterna** [comment]
I have already commented on this in support in the main server.

**Comment by Mathizsias** [comment]
Songs when played with !local start are not pre-shuffled and always appear to start with the same song from the folder. Even though the bot is configured to !shuffle. The same !shuffle works fine for !play.

**Comment by fixator10** [comment]
There is some probability that lavalink WS shutdown happens indefinitely, unless SIGKILL happens.

Approximate reproduce steps:
```md
1. Run Red with audio with some usage for some time (probably let it play on some servers)
2. Run `await bot.shutdown(restart=True)`
3. [V3/edge]: Red will stop on `[INFO] red.Audio.WS.LLServer: Shutdown Lavalink WS.`
4. ^ that will continue indefinitely until SIGKILL is given:
   [2021-04-04 00:39:53] [INFO] red.Audio.WS.LLServer: Shutdown Lavalink WS.
   [2021-04-04 00:40:44] [INFO] red.main: Signals.SIGTERM received. Quitting...
   [2021-04-04 00:40:44] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
   [2021-04-04 00:40:44] [INFO] red.main: Please wait, cleaning up a bit more
   Apr 04 04:40:54 systemd[1]: kurisuv3.service: State 'stop-sigterm' timed out. Killing.
   Apr 04 04:40:54 systemd[1]: kurisuv3.service: Killing process 7935 (python3.8) with signal SIGKILL.
   Apr 04 04:40:54 systemd[1]: kurisuv3.service: Main process exited, code=killed, status=9/KILL
   Apr 04 04:40:54 systemd[1]: kurisuv3.service: Failed with result 'timeout'.
```

**Comment by Drapersniper** [comment]
> There is some probability that lavalink WS shutdown happens indefinitely, unless SIGKILL happens.
> 
> Approximate reproduce steps:
> 
> ```lisp
> 1. Run Red with audio with some usage for some time (probably let it play on some servers)
> 2. Run `await bot.shutdown(restart=True)`
> 3. [V3/edge]: Red will stop on `[INFO] red.Audio.WS.LLServer: Shutdown Lavalink WS.`
> 4. ^ that will continue indefinitely until SIGKILL is given:
>    [2021-04-04 00:39:53] [INFO] red.Audio.WS.LLServer: Shutdown Lavalink WS.
>    [2021-04-04 00:40:44] [INFO] red.main: Signals.SIGTERM received. Quitting...
>    [2021-04-04 00:40:44] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
>    [2021-04-04 00:40:44] [INFO] red.main: Please wait, cleaning up a bit more
>    Apr 04 04:40:54 systemd[1]: kurisuv3.service: State 'stop-sigterm' timed out. Killing.
>    Apr 04 04:40:54 systemd[1]: kurisuv3.service: Killing process 7935 (python3.8) with signal SIGKILL.
>    Apr 04 04:40:54 systemd[1]: kurisuv3.service: Main process exited, code=killed, status=9/KILL
>    Apr 04 04:40:54 systemd[1]: kurisuv3.service: Failed with result 'timeout'.
> ```

I meant here https://github.com/Cog-Creators/Red-DiscordBot/pull/4565 Fixator, but its fine. i just tested edge and no longer reproducing if the issue persist after the latest update give me a shout on the PR.

**Comment by aikaterna** [comment]
Just adding a link back to https://github.com/Cog-Creators/Red-DiscordBot/issues/3492 here as I saw it wasn't linked. I ran into this myself today where I missed the loading message where audio was loading in Spotify tracks.
- play a spotify playlist
- bot is still enqueing
- run [p]stop
- bot stops playback of current song, keeps feeding in converted songs as it keeps going

**Comment by Technetium1** [comment]
It would be nice to be able to delete large amounts of tracks from the playlist. For example `40-50,52` or `40-50|52`. Might be better to use the bar to keep format with the current request for playing multiple tracks, but it feels most natural to use a comma for both.

**Comment by Drapersniper** [comment]
Note to self: You fucking moron yes its jacks fault but you should make better usage on destination in the arg parse logic ... fix yo shit.

**Comment by ltzmax** [comment]
Add a possible way to toggle notify to a channel, example `[p]audioset notify #testing`.

**Comment by aikaterna** [comment]
> Add a possible way to toggle notify to a channel, example `[p]audioset notify #testing`.

This is already listed in the main description of this topic as "setting a lock on the audio set notify channel via this method".

**Comment by Drapersniper** [comment]
Closing, this one is becoming ungodly; if i missed anything from #5075  feel free to bring it over there.
