### ISSUE TITLE
[Mute] Tracking features

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#3270]
After 3.2, we'll be opening a few features branches to allow things to be worked on in parallel a bit easier.

This tracks what will go into feature/mutes

These features are mandatory for a release containing the feature overhaul:

- [ ] Temporary Mutes
- [ ] Preventing Mute dodging
- [ ] Intelligent permission calculation

These features may come in as an addition later on or in the intial version:
- [ ] Customization of which perms are muted
- [ ] Optional Intelligent calculation of effective mutes
- [ ] Better handling of various cases when bulk mutes are applied

This will allow incremental work, while only merging it back into dev once ready to prevent it from becoming a blocker to releases without requiring a large diff review to accomplish.

All work on this is taking place on the V3/feature/mutes branch.

This issue replaces issues: #1607,#1852,#2103

**Comment by mikeshardmind** [comment]
I've gone ahead and updated this to list what we need to have this ready for release, and which things are nice extras but can be added on later so long as we design the initial portion with that in mind.
