### ISSUE TITLE
We need better issue/pull request templates

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3750]
*How better?* I don't know!

Currently this issue contains only what *I think* could be useful, this needs more discussion but there are plenty things we could improve in our templates.

New templates that could be added:
- [x] Issue template for enhancements
- [ ] Issue template for documentation (?)

Improvements to existing templates that we could use:
- [ ] Checklist in pull request template, for example:
  - If code changes were made, they have been tested
  - I've updated the documentation (if applies)
  - If this PR fixes an issue, I referenced them in the PR's description
  - My code follow the code style of this project (Black)
  - etc.
- [ ] Mention that lack of issue (or other prior discussion) may result in rejection
- [ ] Maybe add more types to choose from in pull request template (assuming the checklist from previous point won't just completely replace it)

**Comment by Kowlin** [comment]
Theoretically done in #4784?

**Comment by Jackenmen** [comment]
Part of it is done (which I've already updated in the issue description earlier), but not the whole issue as the PR template is still the same.
There's also the question of whether we want a docs template. I don't think we really need one considering it can easily fall under other available templates, but ¯\_(ツ)_/¯
