### ISSUE TITLE
Future Audio Work (2021)

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#5075]
This issue is to gather features to be suggested for or worked on for Audio this supersedes and replaces #2940.

### Open Issues: 
- [ ] Lavalink status (Issue - #1811)
- [ ] Document Lavalink setup with multiple instances (Issue - #2843) (This could also send a message to the bot owner)

### TODO:
- [ ] Queue: move songs up and down the list by number of songs (Issue - #621)
- [ ] Break Search command into multiple subcommands
- [ ] Wastebin lists of links to tracks
- [ ] Remove multiple songs at once
- [ ] Make Queue aware when enqueuing playlists and/or albums
- [ ] Add more dispatches
- [ ] Add more public APIs to allow for more Audio add-ons 
- [ ] Make use of partial tracks to reduce memory footpring + youtube api calls
- [ ] Remove multiple songs from a playlist - (Req - #2940)

### Requests:
- [ ] Make playlist remember where it was stopped? (Issue - #1544)
- [ ] Google Play Music Support (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md)
- [ ] SFX support
- [ ] `[p]prev` Can go back multiple songs > This will be easier if #366 is addressed - (Req - #2940)
- [ ] Local: M3U/M3U8/PLS/XSPF/WPL/ASX/iTunes Playlists support (#620) (make custom parser or contribute to Lavaplayer/Lavalink)
- [ ] Parse tracks out of a M3U and PLS url
- [ ] Repeat the whole queue

### Maybe:
- [ ]  A thumbsup/thumbsdown on a np message to make a song play more frequently on a playlist in tandem with the playlist checking on #1544, + skip stats (playlist playing stat saving/management)
- [ ] Lyrics support
- [ ] Expand Spotify playlist support to use SoundCloud API
- [ ] Jukebox price to be charged per song instead of per command?
- [ ] Pillow Audio 😝 
- [ ] Add RPC functionality; information on doing this at Req - #3741)
- [ ] add `[p]makeplaylist` that enqueue n number of recently played tracks in the server
- [ ] add `[p]playstric <author> || <track name>` which would allow using Global Cache and JDA cache directly.
- [ ] Add special casing for Live stream playlists
- [ ] Volume ranges -(Req - #2940)
- [ ] Youtube music api support - (Req - #2940)
- [ ] Localtracks ensure shuffle, this will slowdown the enqueueing potentially - (Req - #2940)

### TODO Priority in order
3. Bulk playlist start - (Req - #2940)
4. Autojoin/bind (a command to bind the bot to a text channel and a voice channel for the duration of the audio session), also setting a lock on the audio set notify channel via this method, pinned queue - (Red - #2940)
5.  Configurable limit on max concurrent audio streams (Issue - #272)
6.  More Spotify functionality using their API
7. Spotify Search command
8. Absolute Vote toggle (Voting system that DJ's can't bypass)
9. Auto Join a music channel

## In Alpha (https://github.com/Drapersniper/Audio)
- [x] Add a `[p]playmix <url>` command based on the newly discovered behaviour of youtube mix playlists - (Req - #2940)
- [x] `[p]play` and `[p]playlist append` commands to bulk enque multiple songs, e.g  `[p]play 1|2|3, (Req - #2940)
- [x] Allow the installation of Specified Lavalink servers or to auto update the managed node.
- [x] Disallow commands while deafened - (Req - #2940)

### With Open PRS:
- [x] `[p]audioset server role` To accept a list of roles (FR - #5096) (PR -#5061)
- [x] Set maximum allowed volume (FR- #5097) (PR -#5061)
- [x] Channel specific volume settings (FR- #5097) (PR -#5061)
- [x] Effects (FR - #5105) (PR - #5016)
- [x] Global EQs - (Req - #2940) (FR - #5105) (PR - #5016)
  - Not implemented exactly as requested but some global presets have been added (Piano, Metal, Bassboost, Nightcore, Vaporwave and Synth EQ presets)
- [x] Configurable maximum queue size - Places where the Queue is Controllate already been added, now need to add a command to set it. (FR- #5098)  (PR -#5061)
- [x] Global empty disconnect - (Req - #2940) (FR - #5099) (PR -#5061)
- [x] Global empty pause (Req - #2940) (FR - #5100) (PR -#5061)
- [x] Allow users to modify application.yaml (FR-#5101)(PR - #5061)
- [x] Auto connect to an existing node in case of a failure due to port already taken (FR - #5057) (PR -#5067)
- [x] Improve audio performance by caching config calls (PR -#5061)
- [x] Commands for multi node support - (PR - #5061)
- [x] Revamp of `[p]audioset` Commands may be longer but are more intuitive, don't like it? make aliases with the alias code. - (FR - #5102 )(PR -#5061)
- [x] Allow Bot owner to disconnect all, active, idle or specific players. - (FR - #5102) (PR -#5061)
- [x] Add a command to see the latest Red-Lavalink server releases with the URL, version and published date. -  (FR - #5104) (PR -#5061)

#### What about sfx?
- sfx can be found (unapproved) at: https://github.com/baiumbg/baiumbg-Cogs . Use at your own risk.

#### Want to suggest something?
- Just leave a comment below!

**Comment by Drapersniper** [comment]
Not closing this one as it should still be benefitial for whoever picks up audio maintenance now.
