### ISSUE TITLE
[Audio] Suggestions for rewrite

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#623]
We're gonna use this as a collection board for any/all current or future audio suggestions.
- [ ] sfx #622 
- [x] better queue control #621 
- [x] local playlist files #620 
- [x] play individual local files
- [x] jump to time #619 
- [x] web radio stuff (which is the same thing as livestream) #548
- [x] event system in place to allow for channel based notifications #284
- [ ] configurable limit on max concurrent audio streams #272 
- [x] better soundcloud/yt playlist support #265
- [x] walk local playlists (sub-folder support) #270
- [x] auto pause if empty? #721 
- [x] current time in [p]song #644
- [x] ability to update (automatically?) saved playlists #644
- [x] allow skipping multiple songs #1845

*kill me now*

**Comment by tekulvw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [General Audio rewrite](https://trello.com/c/7G31eLks/1-general-audio-rewrite)

**Comment by Fr6jDJF** [comment]
- #366 
- Downloading status/response so ppl don't re-queue (large tracks x100MB)

**Comment by Jonny0181** [comment]
Maybe some sort of progress on the [p]song command out of the duration of the song, and something to be able to scroll through the queue with reactions when It doesn't show the whole queue?

**Comment by Br0kenMaverick** [comment]
An embed control for a music dedicated text channel, with:
Info:
-Now playing
-Next 5 or 10 queued songs
Reaction buttons:
-play, pause, stop, volume.
-help

Something like this, but well put together :'D https://cdn.discordapp.com/attachments/295226583936008192/295227238423461890/Captura.PNG

**Comment by PJP2810** [comment]
The ability to ADD a local list to the current queue (at least whilst it's playing from local music) e.g. [p]local start Playlist1 then whilst that is playing [p]local add Playlist2 Also if/when this is added it would make sense to be able to play multiple at once with something like [p]local start Playlist1 Playlist2 etc

**Comment by rtil5** [comment]
a couple things if they haven't already been suggested: 

- queue pagination
- ability for anyone to skip/delete their own queued songs
- more information on each song (length, who queued it)
- in general a more verbose bot that lets users know what's playing and when, etc.

nadekobot and erisbot have good examples of these queuing features

**Comment by PJP2810** [comment]
Fix emptydisconnect.

Also, have the option for user chosen time for emptydisconnect. e.g. [p]audioset emptydisconnect 2 (after 2 mins dc)

**Comment by palmtree5** [comment]
I'd also suggest better error handling for errors from youtube-dl (i.e. rather than just dumping out a somewhat cryptic error message, try to figure out the error's meaning and give the user a readable explanation of what went wrong)

**Comment by skeith** [comment]
suggesting

- save current queue as a playlist
- list songs from a playlist

**Comment by palmtree5** [comment]
Suggestion: make audio usable in DM calls

**Comment by Jan200101** [comment]
Only friends can get into DM calls with you and bots cant be your friend

**Comment by palmtree5** [comment]
I forgot that was a thing

**Comment by tekulvw** [comment]
For those wondering, I'll be getting back into this in mid-late May. My work semester has been keeping life busy and getting back to school should alleviate some of that. If anybody would like to contribute (ha!) shoot me a pm on discord.

**Comment by lilliliilil** [comment]
Autoplay feature would be nice (auto-queue related songs when playlist is empty).

**Comment by Br0kenMaverick** [comment]
Support for Youtube Mix links.

**Comment by H3xadecimal** [comment]
livestream support
option to not cache audio instead stream it directly.

**Comment by EmmaSimon** [comment]
Is there a reason why we can't (or is there some hidden way to) play local songs without using local playlists? As in `!local play song.mp3`, if you just want a specific one? I could probably put together a pull request in the next few days, but I'm not sure if it should be a part of `!local play`, or if it should be a new subcommand within !local.

**Comment by tekulvw** [comment]
@EmmaSimon There is no reason why not, just added it to the list

**Comment by tekulvw** [comment]
@GitHubMathi that was added to audio in #765

**Comment by EmmaSimon** [comment]
@tekulvw I added it in #783 if you want to take a look, also fixed #270 while I was poking around.

**Comment by josipledic** [comment]
Livestream support would be really nice, especially after so many 24/7 music streams popped up on Youtube in the last weeks/months.

**Comment by Aioxas** [comment]
Here is a way to fix the outstanding issue regarding SC Likes (most likely what causes it) not being added to the saved playlist due to 'dict has no "url" attribute'.

Whether it's fixed in V3 or not, here's the could-be fix for existing v2 users.

Also, if "playlist" or "sets" or "likes" in url_or_search_terms in play command, make it tell the user to add it to a playlist in Red first then try playing that playlist. 

Failure to do so will cause the bot to either time out (because the bot sees that it's not playing anything and disconnects due to emptydisconnect) or it will get an 403 Error in the case of SC for downloading too many files. It will also get a KeyError in checking if the server.id is in self.downloaders if it disconnects (because of emptydisconnect) during parsing.

```python

    async def _parse_sc_playlist(self, url):
        playlist = []
        d = Downloader(url)
        d.start()

        while d.is_alive():
            await asyncio.sleep(0.5)

        for entry in d.song.entries:
            if entry["url"][4] != "s":
                song_url = "https{}".format(entry["url"][4:])
                playlist.append(song_url)
            else:
                try: # Tries to do it the normal way
                    playlist.append(entry.url)
                except AttributeError: # Error Type. Tries again using a normal dict attribute
                    playlist.append(entry["url"])

        return playlist

**Comment by Kamiden** [comment]
A 'repeat one' function for local files would be great. Maybe just for anything in the queue. Linus Bot had this, but Linus doesn't exist anymore....

**Comment by Just-Insane** [comment]
Integration with Google Play Music Desktop Player's API. Documentation can be found here: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md

**Comment by Jan200101** [comment]
*for the google play music intergration a wrapper like [gmusicapi](https://github.com/simon-weber/gmusicapi/tree/master) could be used to control it*

**Comment by zinefer** [comment]
Suggestion: channel specific volume settings?

**Comment by laggron42** [comment]
What about a function that will make the bot join a selected channel on cog load? Like a music channel. We could set predetermined settings with that, like play a song or a playlist and loop it, set the volume...

**Comment by XT3RM1N8R** [comment]
I highly recommend expanding standard playlist handling and track search to simultaneously handle both local track and YT/SC tracks. This would go with the queue functionality, as well. 

Additionally, having a smart track/album search that can look for substrings in names would be very helpful, as I've found that many users either don't know the full track/album names or they don't know to input the entire name. I have actually solved this part on a local branch and would be willing to share.

**Comment by jonyroda97** [comment]
add suggestions on #644 
- Multi playlists on queue.
Random playing between the playlists queued (but not like 1 from playlist A other from playlist B and then from playlist A again. Really randomised from all the songs).

- Add a better queued response. 
This is good when you want to know who queued the sound and have the bot command messages delete enabled. Maybe something like: 
"\<user> queued in  \#<queue_position> \<title>
 (\<link>)"
Example: 
jonyroda97 queued in  \#800 **_Post Malone - Congratulations ft. Quavo_**
(https://www.youtube.com/watch?v=SC4xMk98Pdc)


and on #366 
- Replay queued history by day
Allows mods to manage/export replays as general playlist.
General users may start replays.
Auto cleanup old unused replays

**Comment by skeith** [comment]
Requesting Absolute Vote toggle

What it do?
When toggled ON, this ignore everyone with instant skip power, so they are counted for skip vote. Of course, bot owner still an exception.

**Comment by Curvol** [comment]
So, I have a text file with hundreds of _**pPlay Links/Artist - Song Name**_ from songs my group has collected to play in the background of our adventures and hijinks. 

The first thought could be to make a text playlist to save all these for instant play! Wrong. Can't do that cause we need to add another song that isn't on the list! Doing that would make it to the very top because it won't shuffle with the playlist! 

Alright then let's just paste them all with the play command- one by one? 

okay uh, lets get a bot to say the comma- bots don't listen to bots huh?

alright, fuck it. I'll type out all the songs we want into a format I can copy and paste them one by one into discord. SO I CAN ADD SONGS, AND SHUFFLE ALL OF THEM.

So these days I'm using a macro to highlight the line and copy, alt tab to discord, enter paste, alt tab times infinite. This honestly wouldn't be the worst aside from the temporary lockdown of my computer, but if a song ends and a command is entered while the bots downloading ITS FULL QUEUE WIPE. You downloading a patch and changing songs at the same ti-QUEUE WIPE WEBSOCKET CRASH GAME OVER MAN.

I just wanted to be a nice lobby leader with a nice base queue of songs everyone could join in on.

So if there were a more, open queue kind of playlist option I could save links in while allowing people to queue songs up then shuffle, I wouldn't think twice about doing anything you want with me.  I love you guys and keep up the hard work.

**Comment by endms3231** [comment]
How about using the real-time streaming URL as a parameter to listen to the broadcast with audio?

**Comment by skeith** [comment]
@Second-Epsilon that's planned IIRC

**Comment by Second-Epsilon** [comment]
I see! that's great!

**Comment by endms3231** [comment]
@skeith I see! that's great!

**Comment by Ray-MRQ** [comment]
have audio locked to a channel so it isn't used else where.

**Comment by palmtree5** [comment]
That should be possible with the permissions cog that's coming (see #1548 for more info on that)

**Comment by Ray-MRQ** [comment]
I understand that. but shouldn't music lock channel be core already? like a lot of other bits has that feature to prevent spam across channels without using something else.

**Comment by Tobotimus** [comment]
Superseded by #2494
